//+build !swipe

// Code generated by Swipe v1.13.1. DO NOT EDIT.

//go:generate swipe
package assembly

import (
	"github.com/swipe-io/swipe/fixtures/model"
	"github.com/swipe-io/swipe/fixtures/user"
)

func AssemblyFromDTOUserToModelUser(from user.User) (to model.User) {
	to = model.User{Name: func(from user.User) string {
		return "OK"
	}(from), Password: from.Password, Point: model.Point{T: from.Point.Type, Coordinates: from.Point.Coordinates}}
	return
}

func AssemblyFromModelUserToDTOUser(from model.User) (to user.User) {
	to = user.User{Name: from.Name, Point: user.GeoJSON{Type: from.Point.T, Coordinates: from.Point.Coordinates}}
	return
}
