//+build !swipe

// Code generated by Swipe v2.0.0-rc4. DO NOT EDIT.

package app

import (
	"bytes"
	"context"
	"fmt"
	"io/ioutil"
	"net"
	http2 "net/http"
	"net/url"
	"strings"

	"github.com/go-kit/kit/transport/http"
	"github.com/pquerna/ffjson/ffjson"
	"github.com/swipe-io/swipe/v2/fixture/ServiceRESTMultiIdenticalInterface/app/controller/app1"
	"github.com/swipe-io/swipe/v2/fixture/ServiceRESTMultiIdenticalInterface/app/controller/app2"
)

func NewClientRESTApp1(tgt string, options ...ClientOption) (app1.App, error) {
	opts := &clientOpts{}
	c := &clientApp1{}
	for _, o := range options {
		o(opts)
	}
	if strings.HasPrefix(tgt, "[") {
		host, port, err := net.SplitHostPort(tgt)
		if err != nil {
			return nil, err
		}
		tgt = host + ":" + port
	}
	u, err := url.Parse(tgt)
	if err != nil {
		return nil, err
	}
	if u.Scheme == "" {
		u.Scheme = "https"
	}
	c.app1CreateEndpoint = http.NewClient(
		http2.MethodPost,
		u,
		func(_ context.Context, r *http2.Request, request interface{}) error {
			req, ok := request.(App1CreateCreateRequest)
			if !ok {
				return fmt.Errorf("couldn't assert request as App1CreateCreateRequest, got %T", request)
			}
			r.Method = http2.MethodPost
			r.URL.Path += "/app1/create"
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.Body = ioutil.NopCloser(bytes.NewBuffer(data))
			return nil
		},
		func(_ context.Context, r *http2.Response) (interface{}, error) {
			if statusCode := r.StatusCode; statusCode != http2.StatusOK {
				return nil, app1CreateErrorDecode(statusCode)
			}
			return nil, nil
		},
		append(opts.genericClientOption, opts.app1CreateClientOption...)...,
	).Endpoint()
	c.app1CreateEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.app1CreateEndpointMiddleware...))(c.app1CreateEndpoint)
	return c, nil
}

func NewClientRESTApp2(tgt string, options ...ClientOption) (app2.App, error) {
	opts := &clientOpts{}
	c := &clientApp2{}
	for _, o := range options {
		o(opts)
	}
	if strings.HasPrefix(tgt, "[") {
		host, port, err := net.SplitHostPort(tgt)
		if err != nil {
			return nil, err
		}
		tgt = host + ":" + port
	}
	u, err := url.Parse(tgt)
	if err != nil {
		return nil, err
	}
	if u.Scheme == "" {
		u.Scheme = "https"
	}
	c.app2CreateEndpoint = http.NewClient(
		http2.MethodPost,
		u,
		func(_ context.Context, r *http2.Request, request interface{}) error {
			req, ok := request.(App2CreateCreateRequest)
			if !ok {
				return fmt.Errorf("couldn't assert request as App2CreateCreateRequest, got %T", request)
			}
			r.Method = http2.MethodPost
			r.URL.Path += "/app2/create"
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.Body = ioutil.NopCloser(bytes.NewBuffer(data))
			return nil
		},
		func(_ context.Context, r *http2.Response) (interface{}, error) {
			if statusCode := r.StatusCode; statusCode != http2.StatusOK {
				return nil, app2CreateErrorDecode(statusCode)
			}
			return nil, nil
		},
		append(opts.genericClientOption, opts.app2CreateClientOption...)...,
	).Endpoint()
	c.app2CreateEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.app2CreateEndpointMiddleware...))(c.app2CreateEndpoint)
	return c, nil
}
