// Code generated by Swipe v1.22.2. DO NOT EDIT.

export class JSONRPCError extends Error {
  constructor(message, name, code, data) {
    super(message);
    this.name = name;
    this.code = code;
    this.data = data;
  }
}
class JSONRPCClient {
  /**
   *
   * @param {*} transport
   */
  constructor(transport) {
    this._transport = transport;
    this._requestID = 0;
    this._scheduleRequests = {};
    this._commitTimerID = null;
    this._beforeRequest = null;
  }
  beforeRequest(fn) {
    this._beforeRequest = fn;
  }
  __scheduleCommit() {
    if (this._commitTimerID) {
      clearTimeout(this._commitTimerID);
    }
    this._commitTimerID = setTimeout(() => {
      this._commitTimerID = null;
      const scheduleRequests = { ...this._scheduleRequests };
      this._scheduleRequests = {};
      let requests = [];
      for (let key in scheduleRequests) {
        requests.push(scheduleRequests[key].request);
      }
      this.__doRequest(requests)
        .then(responses => {
          for (let i = 0; i < responses.length; i++) {
            if (responses[i].error) {
              scheduleRequests[responses[i].id].reject(
                convertError(responses[i].error)
              );
              continue;
            }
            scheduleRequests[responses[i].id].resolve(responses[i].result);
          }
        })
        .catch(e => {
          for (let key in requests) {
            if (!requests.hasOwnProperty(key)) {
              continue;
            }
            if (scheduleRequests.hasOwnProperty(requests[key].id)) {
              scheduleRequests[requests[key].id].reject(e);
            }
          }
        });
    }, 0);
  }
  makeJSONRPCRequest(id, method, params) {
    return {
      jsonrpc: "2.0",
      id: id,
      method: method,
      params: params
    };
  }
  __scheduleRequest(method, params) {
    const p = new Promise((resolve, reject) => {
      const request = this.makeJSONRPCRequest(
        this.__requestIDGenerate(),
        method,
        params
      );
      this._scheduleRequests[request.id] = {
        request,
        resolve,
        reject
      };
    });
    this.__scheduleCommit();
    return p;
  }
  __doRequest(request) {
    return this._transport.doRequest(request);
  }
  __requestIDGenerate() {
    return ++this._requestID;
  }
}
export default class extends JSONRPCClient {
  /**
   *  Create new item of item.
   *
   * @param {string} name
   * @param {Array.<number>} data
   **/
  create(name, data) {
    return this.__scheduleRequest("create", { name: name, data: data });
  }
  /**
   * @param {number} id
   * @return {PromiseLike<{a: string, b: string}>}
   **/
  delete(id) {
    return this.__scheduleRequest("delete", { id: id });
  }
  /**
   *  Get item.
   *
   * @param {number} id
   * @param {string} name
   * @param {string} fname
   * @param {number} price
   * @param {number} n
   * @param {number} b
   * @param {number} c
   * @return {PromiseLike<{data: {
   *  id: string,
   *  name: string,
   *  password: string,
   *  point: {
   *    coordinates200: Array.<number>
   *  },
   *  last_seen: string,
   *  photo: Array.<number>,
   *  profile: {
   *    phone: string
   *  },
   *  created_at: string,
   *  updated_at: string
   *  }}>}
   **/
  get(id, name, fname, price, n, b, c) {
    return this.__scheduleRequest("get", {
      id: id,
      name: name,
      fname: fname,
      price: price,
      n: n,
      b: b,
      c: c
    });
  }
  /**
   *  GetAll more comment and more and more comment and more and more comment and more.
   *  New line comment.
   *
   * @return {PromiseLike<Array.<{
   *  id: string,
   *  name: string,
   *  password: string,
   *  point: {
   *    coordinates200: Array.<number>
   *  },
   *  last_seen: string,
   *  photo: Array.<number>,
   *  profile: {
   *    phone: string
   *  },
   *  created_at: string,
   *  updated_at: string
   *  }>>}
   **/
  getAll() {
    return this.__scheduleRequest("getAll", {});
  }
  /**
   * @param {Object.<string, *>} data
   * @param {*} ss
   * @return {PromiseLike<{states: Object.<string, Object.<string, Array.<string>>>}>}
   **/
  testMethod(data, ss) {
    return this.__scheduleRequest("testMethod", { data: data, ss: ss });
  }
  /**
   * @param {string} ns
   * @param {string} utype
   * @param {string} user
   * @param {string} restype
   * @param {string} resource
   * @param {string} permission
   **/
  testMethod2(ns, utype, user, restype, resource, permission) {
    return this.__scheduleRequest("testMethod2", {
      ns: ns,
      utype: utype,
      user: user,
      restype: restype,
      resource: resource,
      permission: permission
    });
  }
}
export class ErrUnauthorizedError extends JSONRPCError {
  constructor(message, data) {
    super(message, "ErrUnauthorizedError", -32001, data);
  }
}
function convertError(e) {
  switch (e.code) {
    default:
      return new JSONRPCError(e.message, "UnknownError", e.code, e.data);
    case -32001:
      return new ErrUnauthorizedError(e.message, e.data);
  }
}
