//+build !swipe

// Code generated by Swipe v2.0.0-rc4. DO NOT EDIT.

package app

import (
	"context"
	"time"

	"github.com/go-kit/kit/log"
)

type ALoggingMiddleware struct {
	next   InterfaceA
	logger log.Logger
}

func (s *ALoggingMiddleware) TestMethod() {
	s.next.TestMethod()
}

func NewLoggingAMiddleware(s InterfaceA, logger log.Logger) InterfaceA {
	return &ALoggingMiddleware{next: s, logger: logger}
}

type BLoggingMiddleware struct {
	next   InterfaceB
	logger log.Logger
}

func (s *BLoggingMiddleware) Create(ctx context.Context, newData Data, name string, data []byte) error {
	var (
		err error
	)
	defer func(now time.Time) {
		logErr := err
		if le, ok := err.(interface{ LogError() error }); ok {
			logErr = le.LogError()
		}
		logger := log.WithPrefix(s.logger, "method", "Create", "took", time.Since(now))
		logger.Log("name", name, "data", len(data), "err", logErr)
	}(time.Now())
	err = s.next.Create(ctx, newData, name, data)
	return err
}

func (s *BLoggingMiddleware) Delete(ctx context.Context, id uint) (string, string, error) {
	var (
		a   string
		b   string
		err error
	)
	a, b, err = s.next.Delete(ctx, id)
	return a, b, err
}

func (s *BLoggingMiddleware) Get(ctx context.Context, id int, name string, fname string, price float32, n int, b int, cc int) (User, error) {
	var (
		result User
		err    error
	)
	result, err = s.next.Get(ctx, id, name, fname, price, n, b, cc)
	return result, err
}

func (s *BLoggingMiddleware) GetAll(ctx context.Context, members Members) ([]*User, error) {
	var (
		result []*User
		err    error
	)
	result, err = s.next.GetAll(ctx, members)
	return result, err
}

func (s *BLoggingMiddleware) TestMethod(data map[string]interface{}, ss interface{}) (map[string]map[int][]string, error) {
	var (
		result map[string]map[int][]string
		err    error
	)
	result, err = s.next.TestMethod(data, ss)
	return result, err
}

func (s *BLoggingMiddleware) TestMethod2(ctx context.Context, ns string, utype string, user string, restype string, resource string, permission string) error {
	var (
		err error
	)
	err = s.next.TestMethod2(ctx, ns, utype, user, restype, resource, permission)
	return err
}

func NewLoggingBMiddleware(s InterfaceB, logger log.Logger) InterfaceB {
	return &BLoggingMiddleware{next: s, logger: logger}
}
