//+build !swipe

// Code generated by Swipe v2.0.0-rc4. DO NOT EDIT.

package app

import (
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/url"
	"strings"

	"github.com/l-vitaly/go-kit/transport/http/jsonrpc"
	"github.com/pquerna/ffjson/ffjson"
)

// Deprecated
func NewClientJSONRPC(tgt string, options ...ClientOption) (InterfaceB, error) {
	return NewClientJSONRPCInterfaceB(tgt, options...)
}
func NewClientJSONRPCInterfaceB(tgt string, options ...ClientOption) (InterfaceB, error) {
	opts := &clientOpts{}
	c := &clientInterfaceB{}
	for _, o := range options {
		o(opts)
	}
	if strings.HasPrefix(tgt, "[") {
		host, port, err := net.SplitHostPort(tgt)
		if err != nil {
			return nil, err
		}
		tgt = host + ":" + port
	}
	u, err := url.Parse(tgt)
	if err != nil {
		return nil, err
	}
	if u.Scheme == "" {
		u.Scheme = "https"
	}
	opts.interfaceBCreateClientOption = append(
		opts.interfaceBCreateClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(CreateRequest)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as CreateRequest, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBCreateErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			return nil, nil
		}),
	)
	c.createEndpoint = jsonrpc.NewClient(
		u,
		"service.create",
		append(opts.genericClientOption, opts.interfaceBCreateClientOption...)...,
	).Endpoint()
	c.createEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBCreateEndpointMiddleware...))(c.createEndpoint)
	opts.interfaceBDeleteClientOption = append(
		opts.interfaceBDeleteClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(DeleteRequest)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as DeleteRequest, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBDeleteErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			var resp DeleteResponse
			err := ffjson.Unmarshal(response.Result, &resp)
			if err != nil {
				return nil, fmt.Errorf("couldn't unmarshal body to DeleteResponse: %s", err)
			}
			return resp, nil
		}),
	)
	c.deleteEndpoint = jsonrpc.NewClient(
		u,
		"service.delete",
		append(opts.genericClientOption, opts.interfaceBDeleteClientOption...)...,
	).Endpoint()
	c.deleteEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBDeleteEndpointMiddleware...))(c.deleteEndpoint)
	opts.interfaceBGetClientOption = append(
		opts.interfaceBGetClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(GetRequest)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as GetRequest, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBGetErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			var resp User
			err := ffjson.Unmarshal(response.Result, &resp)
			if err != nil {
				return nil, fmt.Errorf("couldn't unmarshal body to GetResponse: %s", err)
			}
			return resp, nil
		}),
	)
	c.getEndpoint = jsonrpc.NewClient(
		u,
		"service.get",
		append(opts.genericClientOption, opts.interfaceBGetClientOption...)...,
	).Endpoint()
	c.getEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBGetEndpointMiddleware...))(c.getEndpoint)
	opts.interfaceBGetAllClientOption = append(
		opts.interfaceBGetAllClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(GetAllRequest)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as GetAllRequest, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBGetAllErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			var resp []*User
			err := ffjson.Unmarshal(response.Result, &resp)
			if err != nil {
				return nil, fmt.Errorf("couldn't unmarshal body to GetAllResponse: %s", err)
			}
			return resp, nil
		}),
	)
	c.getAllEndpoint = jsonrpc.NewClient(
		u,
		"service.getAll",
		append(opts.genericClientOption, opts.interfaceBGetAllClientOption...)...,
	).Endpoint()
	c.getAllEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBGetAllEndpointMiddleware...))(c.getAllEndpoint)
	opts.interfaceBTestMethodClientOption = append(
		opts.interfaceBTestMethodClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(TestMethodRequest)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as TestMethodRequest, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBTestMethodErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			var resp map[string]map[int][]string
			err := ffjson.Unmarshal(response.Result, &resp)
			if err != nil {
				return nil, fmt.Errorf("couldn't unmarshal body to TestMethodResponse: %s", err)
			}
			return resp, nil
		}),
	)
	c.testMethodEndpoint = jsonrpc.NewClient(
		u,
		"service.testMethod",
		append(opts.genericClientOption, opts.interfaceBTestMethodClientOption...)...,
	).Endpoint()
	c.testMethodEndpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBTestMethodEndpointMiddleware...))(c.testMethodEndpoint)
	opts.interfaceBTestMethod2ClientOption = append(
		opts.interfaceBTestMethod2ClientOption,
		jsonrpc.ClientRequestEncoder(func(_ context.Context, obj interface{}) (json.RawMessage, error) {
			req, ok := obj.(TestMethod2Request)
			if !ok {
				return nil, fmt.Errorf("couldn't assert request as TestMethod2Request, got %T", obj)
			}
			b, err := ffjson.Marshal(req)
			if err != nil {
				return nil, fmt.Errorf("couldn't marshal request %T: %s", obj, err)
			}
			return b, nil
		}),
		jsonrpc.ClientResponseDecoder(func(_ context.Context, response jsonrpc.Response) (interface{}, error) {
			if response.Error != nil {
				return nil, interfaceBTestMethod2ErrorDecode(response.Error.Code, response.Error.Message, response.Error.Data)
			}
			return nil, nil
		}),
	)
	c.testMethod2Endpoint = jsonrpc.NewClient(
		u,
		"service.testMethod2",
		append(opts.genericClientOption, opts.interfaceBTestMethod2ClientOption...)...,
	).Endpoint()
	c.testMethod2Endpoint = middlewareChain(append(opts.genericEndpointMiddleware, opts.interfaceBTestMethod2EndpointMiddleware...))(c.testMethod2Endpoint)
	return c, nil
}
