//+build !swipe

// Code generated by Swipe v1.23.0. DO NOT EDIT.

//go:generate swipe
package rest

import (
	"context"
	"fmt"
	"github.com/go-kit/kit/endpoint"
	"github.com/l-vitaly/go-kit/transport/fasthttp"
	"github.com/pquerna/ffjson/ffjson"
	"github.com/swipe-io/swipe/fixtures/service"
	"github.com/swipe-io/swipe/fixtures/user"
	fasthttp2 "github.com/valyala/fasthttp"
	"io"
	"net/http"
	"net/url"
	"strconv"
)

type SwipeClientOption func(*clientSwipe)

func SwipeGenericClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.genericClientOption = opt }
}

func SwipeGenericClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.genericEndpointMiddleware = opt }
}

func SwipeCreateClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.createClientOption = opt }
}

func SwipeCreateClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.createEndpointMiddleware = opt }
}

func SwipeDeleteClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.deleteClientOption = opt }
}

func SwipeDeleteClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.deleteEndpointMiddleware = opt }
}

func SwipeGetClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.getClientOption = opt }
}

func SwipeGetClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.getEndpointMiddleware = opt }
}

func SwipeGetAllClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.getAllClientOption = opt }
}

func SwipeGetAllClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.getAllEndpointMiddleware = opt }
}

func SwipeTestMethodClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.testMethodClientOption = opt }
}

func SwipeTestMethodClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.testMethodEndpointMiddleware = opt }
}

func SwipeTestMethod2ClientOptions(opt ...fasthttp.ClientOption) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.testMethod2ClientOption = opt }
}

func SwipeTestMethod2ClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ SwipeClientOption) {
	return func(c *clientSwipe) { c.testMethod2EndpointMiddleware = opt }
}

type clientSwipe struct {
	createEndpoint                endpoint.Endpoint
	createClientOption            []fasthttp.ClientOption
	createEndpointMiddleware      []endpoint.Middleware
	deleteEndpoint                endpoint.Endpoint
	deleteClientOption            []fasthttp.ClientOption
	deleteEndpointMiddleware      []endpoint.Middleware
	getEndpoint                   endpoint.Endpoint
	getClientOption               []fasthttp.ClientOption
	getEndpointMiddleware         []endpoint.Middleware
	getAllEndpoint                endpoint.Endpoint
	getAllClientOption            []fasthttp.ClientOption
	getAllEndpointMiddleware      []endpoint.Middleware
	testMethodEndpoint            endpoint.Endpoint
	testMethodClientOption        []fasthttp.ClientOption
	testMethodEndpointMiddleware  []endpoint.Middleware
	testMethod2Endpoint           endpoint.Endpoint
	testMethod2ClientOption       []fasthttp.ClientOption
	testMethod2EndpointMiddleware []endpoint.Middleware
	genericClientOption           []fasthttp.ClientOption
	genericEndpointMiddleware     []endpoint.Middleware
}

func (c *clientSwipe) Create(ctx context.Context, name string, data []byte) (_ error) {
	_, err := c.createEndpoint(ctx, createRequestSwipe{Name: name, Data: data})
	if err != nil {
		return err
	}
	return nil
}

func (c *clientSwipe) Delete(ctx context.Context, id uint) (_ string, _ string, _ error) {
	resp, err := c.deleteEndpoint(ctx, deleteRequestSwipe{Id: id})
	if err != nil {
		return "", "", err
	}
	response := resp.(deleteResponseSwipe)
	return response.A, response.B, nil
}

func (c *clientSwipe) Get(ctx context.Context, id int, name string, fname string, price float32, n int, b int, c int) (_ user.User, _ error) {
	resp, err := c.getEndpoint(ctx, getRequestSwipe{Id: id, Name: name, Fname: fname, Price: price, N: n, B: b, C: c})
	if err != nil {
		return user.User{}, err
	}
	response := resp.(getResponseSwipe)
	return response.Data, nil
}

func (c *clientSwipe) GetAll(ctx context.Context) (_ []*user.User, _ error) {
	resp, err := c.getAllEndpoint(ctx, nil)
	if err != nil {
		return nil, err
	}
	response := resp.([]*user.User)
	return response, nil
}

func (c *clientSwipe) TestMethod(data map[string]interface{}, ss interface{}) (_ map[string]map[int][]string, _ error) {
	resp, err := c.testMethodEndpoint(context.Background(), testMethodRequestSwipe{Data: data, Ss: ss})
	if err != nil {
		return nil, err
	}
	response := resp.(testMethodResponseSwipe)
	return response.States, nil
}

func (c *clientSwipe) TestMethod2(ctx context.Context, ns string, utype string, user string, restype string, resource string, permission string) (_ error) {
	_, err := c.testMethod2Endpoint(ctx, testMethod2RequestSwipe{Ns: ns, Utype: utype, User: user, Restype: restype, Resource: resource, Permission: permission})
	if err != nil {
		return err
	}
	return nil
}

func NewClientRESTSwipe(tgt string, opts ...SwipeClientOption) (service.Interface, error) {
	c := &clientSwipe{}
	for _, o := range opts {
		o(c)
	}
	u, err := url.Parse(tgt)
	if err != nil {
		return nil, err
	}
	c.createEndpoint = fasthttp.NewClient(
		fasthttp2.MethodPost,
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			req, ok := request.(createRequestSwipe)
			if !ok {
				return fmt.Errorf("couldn't assert request as createRequestSwipe, got %T", request)
			}
			r.Header.SetMethod(fasthttp2.MethodPost)
			r.SetRequestURI(fmt.Sprintf("/users"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			return nil, nil
		},
		append(c.genericClientOption, c.createClientOption...)...,
	).Endpoint()
	c.createEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.createEndpointMiddleware...))(c.createEndpoint)
	c.deleteEndpoint = fasthttp.NewClient(
		fasthttp2.MethodPost,
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			req, ok := request.(deleteRequestSwipe)
			if !ok {
				return fmt.Errorf("couldn't assert request as deleteRequestSwipe, got %T", request)
			}
			r.Header.SetMethod(fasthttp2.MethodPost)
			r.SetRequestURI(fmt.Sprintf("/delete"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp deleteResponseSwipe
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to deleteResponseSwipe: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.deleteClientOption...)...,
	).Endpoint()
	c.deleteEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.deleteEndpointMiddleware...))(c.deleteEndpoint)
	c.getEndpoint = fasthttp.NewClient(
		fasthttp2.MethodGet,
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			req, ok := request.(getRequestSwipe)
			if !ok {
				return fmt.Errorf("couldn't assert request as getRequestSwipe, got %T", request)
			}
			r.Header.SetMethod(fasthttp2.MethodGet)
			r.SetRequestURI(fmt.Sprintf("/users/%s/%s/%s", strconv.FormatInt(int64(req.Id), 10), req.Name, req.Fname))
			q := r.URI().QueryArgs()
			q.Add("price", strconv.FormatFloat(float64(req.Price), 'g', -1, 32))
			q.Add("c", strconv.FormatInt(int64(req.C), 10))
			r.URI().SetQueryString(q.String())
			r.Header.Add("x-num-n", strconv.FormatInt(int64(req.N), 10))
			r.Header.Add("x-num-b", strconv.FormatInt(int64(req.B), 10))
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp getResponseSwipe
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to getResponseSwipe: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.getClientOption...)...,
	).Endpoint()
	c.getEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.getEndpointMiddleware...))(c.getEndpoint)
	c.getAllEndpoint = fasthttp.NewClient(
		fasthttp2.MethodGet,
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			r.Header.SetMethod(fasthttp2.MethodGet)
			r.SetRequestURI(fmt.Sprintf("/users"))
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp []*user.User
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to getAllResponseSwipe: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.getAllClientOption...)...,
	).Endpoint()
	c.getAllEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.getAllEndpointMiddleware...))(c.getAllEndpoint)
	c.testMethodEndpoint = fasthttp.NewClient(
		"POST",
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			req, ok := request.(testMethodRequestSwipe)
			if !ok {
				return fmt.Errorf("couldn't assert request as testMethodRequestSwipe, got %T", request)
			}
			r.Header.SetMethod("POST")
			r.SetRequestURI(fmt.Sprintf("/testMethod"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp testMethodResponseSwipe
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to testMethodResponseSwipe: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.testMethodClientOption...)...,
	).Endpoint()
	c.testMethodEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.testMethodEndpointMiddleware...))(c.testMethodEndpoint)
	c.testMethod2Endpoint = fasthttp.NewClient(
		http.MethodPut,
		u,
		func(_ context.Context, r *fasthttp2.Request, request interface{}) error {
			req, ok := request.(testMethod2RequestSwipe)
			if !ok {
				return fmt.Errorf("couldn't assert request as testMethod2RequestSwipe, got %T", request)
			}
			r.Header.SetMethod(http.MethodPut)
			r.SetRequestURI(fmt.Sprintf("/%s/auth/%s/%s/%s/%s/%s", req.Ns, req.Utype, req.User, req.Restype, req.Resource, req.Permission))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp2.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp2.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			return nil, nil
		},
		append(c.genericClientOption, c.testMethod2ClientOption...)...,
	).Endpoint()
	c.testMethod2Endpoint = middlewareChain(append(c.genericEndpointMiddleware, c.testMethod2EndpointMiddleware...))(c.testMethod2Endpoint)
	return c, nil
}
