//+build !swipe

// Code generated by Swipe v1.13.1. DO NOT EDIT.

//go:generate swipe
package rest

import (
	"context"
	"fmt"
	"github.com/go-kit/kit/endpoint"
	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/metrics"
	prometheus2 "github.com/go-kit/kit/metrics/prometheus"
	fasthttp2 "github.com/l-vitaly/go-kit/transport/fasthttp"
	"github.com/pquerna/ffjson/ffjson"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/qiangxue/fasthttp-routing"
	"github.com/swipe-io/swipe/fixtures/service"
	"github.com/swipe-io/swipe/fixtures/user"
	"github.com/valyala/fasthttp"
	"io"
	"net/url"
	"strconv"
	"time"
)

type EndpointSet struct {
	TestMethodEndpoint endpoint.Endpoint
	CreateEndpoint     endpoint.Endpoint
	DeleteEndpoint     endpoint.Endpoint
	GetEndpoint        endpoint.Endpoint
	GetAllEndpoint     endpoint.Endpoint
}

func MakeEndpointSet(s service.Interface) EndpointSet {
	return EndpointSet{
		CreateEndpoint:     makeCreateEndpoint(s),
		DeleteEndpoint:     makeDeleteEndpoint(s),
		GetEndpoint:        makeGetEndpoint(s),
		GetAllEndpoint:     makeGetAllEndpoint(s),
		TestMethodEndpoint: makeTestMethodEndpoint(s),
	}
}

type createRequestServiceInterface struct {
	Name string `json:"name"`
	Data []byte `json:"data"`
}
type createResponseServiceInterface struct {
}

func makeCreateEndpoint(s service.Interface) endpoint.Endpoint {
	w := func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(createRequestServiceInterface)
		err := s.Create(ctx, req.Name, req.Data)
		if err != nil {
			return nil, err
		}
		return nil, nil
	}
	return w
}

type deleteRequestServiceInterface struct {
	Id uint `json:"id"`
}
type deleteResponseServiceInterface struct {
	A string `json:"a"`
	B string `json:"b"`
}

func makeDeleteEndpoint(s service.Interface) endpoint.Endpoint {
	w := func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(deleteRequestServiceInterface)
		a, b, err := s.Delete(ctx, req.Id)
		if err != nil {
			return nil, err
		}
		return deleteResponseServiceInterface{A: a, B: b}, nil
	}
	return w
}

type getRequestServiceInterface struct {
	Id    int     `json:"id"`
	Name  string  `json:"name"`
	Fname string  `json:"fname"`
	Price float32 `json:"price"`
	N     int     `json:"n"`
}
type getResponseServiceInterface struct {
	Data user.User `json:"data"`
}

func makeGetEndpoint(s service.Interface) endpoint.Endpoint {
	w := func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(getRequestServiceInterface)
		data, err := s.Get(ctx, req.Id, req.Name, req.Fname, req.Price, req.N)
		if err != nil {
			return nil, err
		}
		return getResponseServiceInterface{Data: data}, nil
	}
	return w
}

func makeGetAllEndpoint(s service.Interface) endpoint.Endpoint {
	w := func(ctx context.Context, request interface{}) (interface{}, error) {
		result, err := s.GetAll(ctx)
		if err != nil {
			return nil, err
		}
		return result, nil
	}
	return w
}

type testMethodRequestServiceInterface struct {
	Data map[string]interface{} `json:"data"`
	Ss   interface{}            `json:"ss"`
}

func makeTestMethodEndpoint(s service.Interface) endpoint.Endpoint {
	w := func(ctx context.Context, request interface{}) (interface{}, error) {
		req := request.(testMethodRequestServiceInterface)
		result, err := s.TestMethod(req.Data, req.Ss)
		if err != nil {
			return nil, err
		}
		return result, nil
	}
	return w
}

type loggingMiddlewareServiceInterface struct {
	next   service.Interface
	logger log.Logger
}

func (s *loggingMiddlewareServiceInterface) Create(ctx context.Context, name string, data []byte) (err error) {
	defer func(now time.Time) {
		s.logger.Log("method", "Create", "took", time.Since(now), "name", name, "data", len(data), "err", err)
	}(time.Now())
	return s.next.Create(ctx, name, data)
}

func (s *loggingMiddlewareServiceInterface) Delete(ctx context.Context, id uint) (a string, b string, err error) {
	defer func(now time.Time) {
		s.logger.Log("method", "Delete", "took", time.Since(now), "id", id, "a", a, "b", b, "err", err)
	}(time.Now())
	return s.next.Delete(ctx, id)
}

func (s *loggingMiddlewareServiceInterface) Get(ctx context.Context, id int, name string, fname string, price float32, n int) (data user.User, err error) {
	defer func(now time.Time) {
		s.logger.Log("method", "Get", "took", time.Since(now), "id", id, "name", name, "fname", fname, "price", price, "n", n, "data", data, "err", err)
	}(time.Now())
	return s.next.Get(ctx, id, name, fname, price, n)
}

func (s *loggingMiddlewareServiceInterface) GetAll(ctx context.Context) (result []*user.User, err error) {
	defer func(now time.Time) {
		s.logger.Log("method", "GetAll", "took", time.Since(now), "result", len(result), "err", err)
	}(time.Now())
	return s.next.GetAll(ctx)
}

func (s *loggingMiddlewareServiceInterface) TestMethod(data map[string]interface{}, ss interface{}) (result map[string]string, err error) {
	defer func(now time.Time) {
		s.logger.Log("method", "TestMethod", "took", time.Since(now), "data", len(data), "ss", ss, "result", len(result), "err", err)
	}(time.Now())
	return s.next.TestMethod(data, ss)
}

type instrumentingMiddlewareServiceInterface struct {
	next           service.Interface
	requestCount   metrics.Counter
	requestLatency metrics.Histogram
}

func (s *instrumentingMiddlewareServiceInterface) Create(ctx context.Context, name string, data []byte) (_ error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "Create").Add(1)
		s.requestLatency.With("method", "Create").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.Create(ctx, name, data)
}

func (s *instrumentingMiddlewareServiceInterface) Delete(ctx context.Context, id uint) (a string, b string, _ error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "Delete").Add(1)
		s.requestLatency.With("method", "Delete").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.Delete(ctx, id)
}

func (s *instrumentingMiddlewareServiceInterface) Get(ctx context.Context, id int, name string, fname string, price float32, n int) (data user.User, _ error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "Get").Add(1)
		s.requestLatency.With("method", "Get").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.Get(ctx, id, name, fname, price, n)
}

func (s *instrumentingMiddlewareServiceInterface) GetAll(ctx context.Context) (_ []*user.User, _ error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "GetAll").Add(1)
		s.requestLatency.With("method", "GetAll").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.GetAll(ctx)
}

func (s *instrumentingMiddlewareServiceInterface) TestMethod(data map[string]interface{}, ss interface{}) (_ map[string]string, _ error) {
	defer func(begin time.Time) {
		s.requestCount.With("method", "TestMethod").Add(1)
		s.requestLatency.With("method", "TestMethod").Observe(time.Since(begin).Seconds())
	}(time.Now())
	return s.next.TestMethod(data, ss)
}

type httpError struct {
	code int
}

func (e httpError) Error() string {
	return fasthttp.StatusMessage(e.code)
}
func (e httpError) StatusCode() int {
	return e.code
}
func ErrorDecode(code int) (_ error) {
	switch code {
	default:
		return httpError{code: code}
	case 403:
		return &service.ErrUnauthorized{}
	}
}

func middlewareChain(middlewares []endpoint.Middleware) endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		if len(middlewares) == 0 {
			return next
		}
		outer := middlewares[0]
		others := middlewares[1:]
		for i := len(others) - 1; i >= 0; i-- {
			next = others[i](next)
		}
		return outer(next)
	}
}

type clientServiceInterface struct {
	getEndpoint                  endpoint.Endpoint
	getClientOption              []fasthttp2.ClientOption
	getEndpointMiddleware        []endpoint.Middleware
	getAllEndpoint               endpoint.Endpoint
	getAllClientOption           []fasthttp2.ClientOption
	getAllEndpointMiddleware     []endpoint.Middleware
	testMethodEndpoint           endpoint.Endpoint
	testMethodClientOption       []fasthttp2.ClientOption
	testMethodEndpointMiddleware []endpoint.Middleware
	createEndpoint               endpoint.Endpoint
	createClientOption           []fasthttp2.ClientOption
	createEndpointMiddleware     []endpoint.Middleware
	deleteEndpoint               endpoint.Endpoint
	deleteClientOption           []fasthttp2.ClientOption
	deleteEndpointMiddleware     []endpoint.Middleware
	genericClientOption          []fasthttp2.ClientOption
	genericEndpointMiddleware    []endpoint.Middleware
}

type clientServiceInterfaceOption func(*clientServiceInterface)

func ServiceInterfaceGenericClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.genericClientOption = opt }
}

func ServiceInterfaceGenericClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.genericEndpointMiddleware = opt }
}

func ServiceInterfaceGetClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.getClientOption = opt }
}

func ServiceInterfaceGetClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.getEndpointMiddleware = opt }
}

func ServiceInterfaceGetAllClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.getAllClientOption = opt }
}

func ServiceInterfaceGetAllClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.getAllEndpointMiddleware = opt }
}

func ServiceInterfaceTestMethodClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.testMethodClientOption = opt }
}

func ServiceInterfaceTestMethodClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.testMethodEndpointMiddleware = opt }
}

func ServiceInterfaceCreateClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.createClientOption = opt }
}

func ServiceInterfaceCreateClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.createEndpointMiddleware = opt }
}

func ServiceInterfaceDeleteClientOptions(opt ...fasthttp2.ClientOption) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.deleteClientOption = opt }
}

func ServiceInterfaceDeleteClientEndpointMiddlewares(opt ...endpoint.Middleware) (_ clientServiceInterfaceOption) {
	return func(c *clientServiceInterface) { c.deleteEndpointMiddleware = opt }
}

func (c *clientServiceInterface) Create(ctx context.Context, name string, data []byte) (_ error) {
	_, err := c.createEndpoint(ctx, createRequestServiceInterface{Name: name, Data: data})
	if err != nil {
		return err
	}
	return nil
}

func (c *clientServiceInterface) Delete(ctx context.Context, id uint) (_ string, _ string, _ error) {
	resp, err := c.deleteEndpoint(ctx, deleteRequestServiceInterface{Id: id})
	if err != nil {
		return "", "", err
	}
	response := resp.(deleteResponseServiceInterface)
	return response.A, response.B, nil
}

func (c *clientServiceInterface) Get(ctx context.Context, id int, name string, fname string, price float32, n int) (_ user.User, _ error) {
	resp, err := c.getEndpoint(ctx, getRequestServiceInterface{Id: id, Name: name, Fname: fname, Price: price, N: n})
	if err != nil {
		return user.User{}, err
	}
	response := resp.(getResponseServiceInterface)
	return response.Data, nil
}

func (c *clientServiceInterface) GetAll(ctx context.Context) (_ []*user.User, _ error) {
	resp, err := c.getAllEndpoint(ctx, nil)
	if err != nil {
		return nil, err
	}
	response := resp.([]*user.User)
	return response, nil
}

func (c *clientServiceInterface) TestMethod(data map[string]interface{}, ss interface{}) (_ map[string]string, _ error) {
	resp, err := c.testMethodEndpoint(context.Background(), testMethodRequestServiceInterface{Data: data, Ss: ss})
	if err != nil {
		return nil, err
	}
	response := resp.(map[string]string)
	return response, nil
}

func NewClientRESTServiceInterface(tgt string, opts ...clientServiceInterfaceOption) (service.Interface, error) {
	c := &clientServiceInterface{}
	for _, o := range opts {
		o(c)
	}
	u, err := url.Parse(tgt)
	if err != nil {
		return nil, err
	}
	c.createEndpoint = fasthttp2.NewClient(
		fasthttp.MethodPost,
		u,
		func(_ context.Context, r *fasthttp.Request, request interface{}) error {
			req, ok := request.(createRequestServiceInterface)
			if !ok {
				return fmt.Errorf("couldn't assert request as createRequestServiceInterface, got %T", request)
			}
			r.Header.SetMethod(fasthttp.MethodPost)
			r.SetRequestURI(fmt.Sprintf("/users"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			return nil, nil
		},
		append(c.genericClientOption, c.createClientOption...)...,
	).Endpoint()
	c.createEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.createEndpointMiddleware...))(c.createEndpoint)
	c.deleteEndpoint = fasthttp2.NewClient(
		fasthttp.MethodPost,
		u,
		func(_ context.Context, r *fasthttp.Request, request interface{}) error {
			req, ok := request.(deleteRequestServiceInterface)
			if !ok {
				return fmt.Errorf("couldn't assert request as deleteRequestServiceInterface, got %T", request)
			}
			r.Header.SetMethod(fasthttp.MethodPost)
			r.SetRequestURI(fmt.Sprintf("/delete"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp deleteResponseServiceInterface
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to deleteResponseServiceInterface: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.deleteClientOption...)...,
	).Endpoint()
	c.deleteEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.deleteEndpointMiddleware...))(c.deleteEndpoint)
	c.getEndpoint = fasthttp2.NewClient(
		fasthttp.MethodGet,
		u,
		func(_ context.Context, r *fasthttp.Request, request interface{}) error {
			req, ok := request.(getRequestServiceInterface)
			if !ok {
				return fmt.Errorf("couldn't assert request as getRequestServiceInterface, got %T", request)
			}
			r.Header.SetMethod(fasthttp.MethodGet)
			r.SetRequestURI(fmt.Sprintf("/users/%s", req.Name))
			q := r.URI().QueryArgs()
			q.Add("price", strconv.FormatFloat(float64(req.Price), 'g', -1, 32))
			r.URI().SetQueryString(q.String())
			r.Header.Add("x-num", strconv.FormatInt(int64(req.N), 10))
			return nil
		},
		func(_ context.Context, r *fasthttp.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp getResponseServiceInterface
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to getResponseServiceInterface: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.getClientOption...)...,
	).Endpoint()
	c.getEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.getEndpointMiddleware...))(c.getEndpoint)
	c.getAllEndpoint = fasthttp2.NewClient(
		fasthttp.MethodGet,
		u,
		func(_ context.Context, r *fasthttp.Request, request interface{}) error {
			r.Header.SetMethod(fasthttp.MethodGet)
			r.SetRequestURI(fmt.Sprintf("/users"))
			return nil
		},
		func(_ context.Context, r *fasthttp.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp []*user.User
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to getAllResponseServiceInterface: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.getAllClientOption...)...,
	).Endpoint()
	c.getAllEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.getAllEndpointMiddleware...))(c.getAllEndpoint)
	c.testMethodEndpoint = fasthttp2.NewClient(
		"POST",
		u,
		func(_ context.Context, r *fasthttp.Request, request interface{}) error {
			req, ok := request.(testMethodRequestServiceInterface)
			if !ok {
				return fmt.Errorf("couldn't assert request as testMethodRequestServiceInterface, got %T", request)
			}
			r.Header.SetMethod("POST")
			r.SetRequestURI(fmt.Sprintf("/testMethod"))
			data, err := ffjson.Marshal(req)
			if err != nil {
				return fmt.Errorf("couldn't marshal request %T: %s", req, err)
			}
			r.SetBody(data)
			return nil
		},
		func(_ context.Context, r *fasthttp.Response) (interface{}, error) {
			if statusCode := r.StatusCode(); statusCode != fasthttp.StatusOK {
				return nil, ErrorDecode(statusCode)
			}
			var resp map[string]string
			err := ffjson.Unmarshal(r.Body(), &resp)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to testMethodResponseServiceInterface: %s", err)
			}
			return resp, nil
		},
		append(c.genericClientOption, c.testMethodClientOption...)...,
	).Endpoint()
	c.testMethodEndpoint = middlewareChain(append(c.genericEndpointMiddleware, c.testMethodEndpointMiddleware...))(c.testMethodEndpoint)
	return c, nil
}

type serverServiceInterfaceOption func(*serverServiceInterfaceOpts)
type serverServiceInterfaceOpts struct {
	genericServerOption          []fasthttp2.ServerOption
	genericEndpointMiddleware    []endpoint.Middleware
	deleteServerOption           []fasthttp2.ServerOption
	deleteEndpointMiddleware     []endpoint.Middleware
	getServerOption              []fasthttp2.ServerOption
	getEndpointMiddleware        []endpoint.Middleware
	getAllServerOption           []fasthttp2.ServerOption
	getAllEndpointMiddleware     []endpoint.Middleware
	testMethodServerOption       []fasthttp2.ServerOption
	testMethodEndpointMiddleware []endpoint.Middleware
	createServerOption           []fasthttp2.ServerOption
	createEndpointMiddleware     []endpoint.Middleware
}

func ServiceInterfaceGenericServerOptions(v ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(o *serverServiceInterfaceOpts) { o.genericServerOption = v }
}

func ServiceInterfaceGenericServerEndpointMiddlewares(v ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(o *serverServiceInterfaceOpts) { o.genericEndpointMiddleware = v }
}

func ServiceInterfaceDeleteServerOptions(opt ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.deleteServerOption = opt }
}

func ServiceInterfaceDeleteServerEndpointMiddlewares(opt ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.deleteEndpointMiddleware = opt }
}

func ServiceInterfaceGetServerOptions(opt ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.getServerOption = opt }
}

func ServiceInterfaceGetServerEndpointMiddlewares(opt ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.getEndpointMiddleware = opt }
}

func ServiceInterfaceGetAllServerOptions(opt ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.getAllServerOption = opt }
}

func ServiceInterfaceGetAllServerEndpointMiddlewares(opt ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.getAllEndpointMiddleware = opt }
}

func ServiceInterfaceTestMethodServerOptions(opt ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.testMethodServerOption = opt }
}

func ServiceInterfaceTestMethodServerEndpointMiddlewares(opt ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.testMethodEndpointMiddleware = opt }
}

func ServiceInterfaceCreateServerOptions(opt ...fasthttp2.ServerOption) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.createServerOption = opt }
}

func ServiceInterfaceCreateServerEndpointMiddlewares(opt ...endpoint.Middleware) (_ serverServiceInterfaceOption) {
	return func(c *serverServiceInterfaceOpts) { c.createEndpointMiddleware = opt }
}

// HTTP REST Transport
type errorWrapper struct {
	Error string `json:"error"`
}

func encodeResponseHTTPServiceInterface(ctx context.Context, w *fasthttp.Response, response interface{}) error {
	h := w.Header
	h.Set("Content-Type", "application/json; charset=utf-8")
	if e, ok := response.(endpoint.Failer); ok && e.Failed() != nil {
		data, err := ffjson.Marshal(errorWrapper{Error: e.Failed().Error()})
		if err != nil {
			return err
		}
		w.SetBody(data)
		return nil
	}
	data, err := ffjson.Marshal(response)
	if err != nil {
		return err
	}
	w.SetBody(data)
	return nil
}

func MakeHandlerRESTServiceInterface(s service.Interface, logger log.Logger, opts ...serverServiceInterfaceOption) (fasthttp.RequestHandler, error) {
	sopt := &serverServiceInterfaceOpts{}
	for _, o := range opts {
		o(sopt)
	}
	s = &loggingMiddlewareServiceInterface{next: s, logger: logger}
	s = &instrumentingMiddlewareServiceInterface{
		next: s,
		requestCount: prometheus2.NewCounterFrom(prometheus.CounterOpts{
			Namespace: "api",
			Subsystem: "api",
			Name:      "request_count",
			Help:      "Number of requests received.",
		}, []string{"method"}),
		requestLatency: prometheus2.NewSummaryFrom(prometheus.SummaryOpts{
			Namespace: "api",
			Subsystem: "api",
			Name:      "request_latency_microseconds",
			Help:      "Total duration of requests in microseconds.",
		}, []string{"method"}),
	}
	ep := MakeEndpointSet(s)
	ep.DeleteEndpoint = middlewareChain(append(sopt.genericEndpointMiddleware, sopt.deleteEndpointMiddleware...))(ep.DeleteEndpoint)
	ep.GetEndpoint = middlewareChain(append(sopt.genericEndpointMiddleware, sopt.getEndpointMiddleware...))(ep.GetEndpoint)
	ep.GetAllEndpoint = middlewareChain(append(sopt.genericEndpointMiddleware, sopt.getAllEndpointMiddleware...))(ep.GetAllEndpoint)
	ep.TestMethodEndpoint = middlewareChain(append(sopt.genericEndpointMiddleware, sopt.testMethodEndpointMiddleware...))(ep.TestMethodEndpoint)
	ep.CreateEndpoint = middlewareChain(append(sopt.genericEndpointMiddleware, sopt.createEndpointMiddleware...))(ep.CreateEndpoint)
	r := routing.New()
	r.To(fasthttp.MethodPost, "/users", fasthttp2.NewServer(
		ep.CreateEndpoint,
		func(ctx context.Context, r *fasthttp.Request) (interface{}, error) {
			var req createRequestServiceInterface
			err := ffjson.Unmarshal(r.Body(), &req)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to createRequestServiceInterface: %s", err)
			}
			return req, nil
		},
		encodeResponseHTTPServiceInterface,
		append(sopt.genericServerOption, sopt.createServerOption...)...,
	).RouterHandle())
	r.To(fasthttp.MethodPost, "/delete", fasthttp2.NewServer(
		ep.DeleteEndpoint,
		func(ctx context.Context, r *fasthttp.Request) (interface{}, error) {
			var req deleteRequestServiceInterface
			err := ffjson.Unmarshal(r.Body(), &req)
			if err != nil && err != io.EOF {
				return nil, fmt.Errorf("couldn't unmarshal body to deleteRequestServiceInterface: %s", err)
			}
			return req, nil
		},
		encodeResponseHTTPServiceInterface,
		append(sopt.genericServerOption, sopt.deleteServerOption...)...,
	).RouterHandle())
	r.To(fasthttp.MethodGet, "/users/<name:[a-z]>", fasthttp2.NewServer(
		ep.GetEndpoint,
		func(ctx context.Context, r *fasthttp.Request) (interface{}, error) {
			var req getRequestServiceInterface
			vars, ok := ctx.Value(fasthttp2.ContextKeyRouter).(*routing.Context)
			if !ok {
				return nil, fmt.Errorf("couldn't assert fasthttp2.ContextKeyRouter to *routing.Context")
			}
			req.Name = vars.Param("name")
			q := r.URI().QueryArgs()
			priceFloat32, err := strconv.ParseFloat(string(q.Peek("price")), 32)
			if err != nil {
				return nil, fmt.Errorf("convert error: %w", err)
			}
			req.Price = float32(priceFloat32)
			nInt, err := strconv.Atoi(string(r.Header.Peek("x-num")))
			if err != nil {
				return nil, fmt.Errorf("convert error: %w", err)
			}
			req.N = int(nInt)
			return req, nil
		},
		encodeResponseHTTPServiceInterface,
		append(sopt.genericServerOption, sopt.getServerOption...)...,
	).RouterHandle())
	r.To(fasthttp.MethodGet, "/users", fasthttp2.NewServer(
		ep.GetAllEndpoint,
		func(ctx context.Context, r *fasthttp.Request) (interface{}, error) {
			return nil, nil
		},
		encodeResponseHTTPServiceInterface,
		append(sopt.genericServerOption, sopt.getAllServerOption...)...,
	).RouterHandle())
	r.To("GET", "/testMethod", fasthttp2.NewServer(
		ep.TestMethodEndpoint,
		func(ctx context.Context, r *fasthttp.Request) (interface{}, error) {
			var req testMethodRequestServiceInterface
			return req, nil
		},
		encodeResponseHTTPServiceInterface,
		append(sopt.genericServerOption, sopt.testMethodServerOption...)...,
	).RouterHandle())
	return r.HandleRequest, nil
}
